// Contact job functions and subfunctions (mirrors the backend
// app/icp_taxonomy.py). FUNCTION_TO_SUBFUNCTIONS groups subfunctions under
// their parent function; JOB_SUBFUNCTIONS is the flattened, deduped list used
// by the multi-select.
export const JOB_FUNCTIONS: string[] = [
  "Accounting",
  "Administrative",
  "Arts and Design",
  "Business Development",
  "Community and Social Services",
  "Consulting",
  "Education",
  "Engineering",
  "Entrepreneurship",
  "Finance",
  "Healthcare Services",
  "Human Resources",
  "Information Technology",
  "Legal",
  "Marketing",
  "Media and Communication",
  "Military and Protective Services",
  "Operations",
  "Product Management",
  "Program and Project Management",
  "Purchasing",
  "Quality Assurance",
  "Real Estate",
  "Research",
  "Sales",
  "Support",
]

export const FUNCTION_TO_SUBFUNCTIONS: Record<string, string[]> = {
  "Accounting": [
    "Accounts Payable",
    "Accounts Receivable",
    "Bookkeeping",
    "Financial Reporting",
    "Payroll",
    "Tax",
  ],
  "Administrative": [
    "Executive Assistant",
    "Office Management",
    "Reception",
    "Data Entry",
  ],
  "Arts and Design": [
    "Graphic Design",
    "Product Design",
    "UX/UI Design",
    "Industrial Design",
  ],
  "Business Development": [
    "Partnerships",
    "Sales Development",
    "Strategic Alliances",
  ],
  "Community and Social Services": [
    "Social Work",
    "Volunteer Coordination",
    "Community Outreach",
  ],
  "Consulting": [
    "Management Consulting",
    "Strategy Consulting",
    "IT Consulting",
  ],
  "Education": [
    "Teaching",
    "Curriculum Development",
    "Academic Administration",
  ],
  "Engineering": [
    "Software Engineering",
    "Hardware Engineering",
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "DevOps",
    "QA Engineering",
    "Data Engineering",
  ],
  "Entrepreneurship": [
    "Founder",
    "Co-Founder",
  ],
  "Finance": [
    "Financial Planning and Analysis",
    "Investment Banking",
    "Treasury",
    "Risk Management",
    "Corporate Finance",
  ],
  "Healthcare Services": [
    "Nursing",
    "Physician",
    "Medical Technician",
    "Healthcare Administration",
  ],
  "Human Resources": [
    "Recruiting",
    "Talent Acquisition",
    "Compensation and Benefits",
    "Learning and Development",
    "HR Business Partner",
  ],
  "Information Technology": [
    "IT Support",
    "Network Administration",
    "Systems Administration",
    "Cybersecurity",
    "Cloud Infrastructure",
    "Database Administration",
  ],
  "Legal": [
    "Corporate Law",
    "Compliance",
    "Contracts",
    "Intellectual Property",
    "Paralegal",
  ],
  "Marketing": [
    "Brand Marketing",
    "Content Marketing",
    "Digital Marketing",
    "Product Marketing",
    "Growth Marketing",
    "Demand Generation",
    "Public Relations",
    "SEO/SEM",
    "Social Media",
  ],
  "Media and Communication": [
    "Journalism",
    "Copywriting",
    "Editorial",
    "Public Relations",
  ],
  "Military and Protective Services": [
    "Security",
    "Law Enforcement",
    "Military",
  ],
  "Operations": [
    "Supply Chain",
    "Logistics",
    "Procurement",
    "Business Operations",
    "Manufacturing Operations",
  ],
  "Product Management": [
    "Product Management",
    "Product Operations",
    "Technical Product Management",
  ],
  "Program and Project Management": [
    "Project Management",
    "Program Management",
    "Scrum Master",
  ],
  "Purchasing": [
    "Procurement",
    "Sourcing",
    "Vendor Management",
  ],
  "Quality Assurance": [
    "Quality Control",
    "Quality Engineering",
    "Compliance",
  ],
  "Real Estate": [
    "Property Management",
    "Real Estate Brokerage",
    "Leasing",
  ],
  "Research": [
    "Market Research",
    "Scientific Research",
    "Data Science",
    "Research and Development",
  ],
  "Sales": [
    "Account Executive",
    "Account Management",
    "Sales Development",
    "Inside Sales",
    "Field Sales",
    "Sales Engineering",
    "Sales Operations",
    "Channel Sales",
    "Customer Success",
  ],
  "Support": [
    "Customer Support",
    "Technical Support",
    "Customer Success",
    "Help Desk",
  ],
}

export const JOB_SUBFUNCTIONS: string[] = [
  "Academic Administration",
  "Account Executive",
  "Account Management",
  "Accounts Payable",
  "Accounts Receivable",
  "Bookkeeping",
  "Brand Marketing",
  "Business Operations",
  "Channel Sales",
  "Civil Engineering",
  "Cloud Infrastructure",
  "Co-Founder",
  "Community Outreach",
  "Compensation and Benefits",
  "Compliance",
  "Content Marketing",
  "Contracts",
  "Copywriting",
  "Corporate Finance",
  "Corporate Law",
  "Curriculum Development",
  "Customer Success",
  "Customer Support",
  "Cybersecurity",
  "Data Engineering",
  "Data Entry",
  "Data Science",
  "Database Administration",
  "Demand Generation",
  "DevOps",
  "Digital Marketing",
  "Editorial",
  "Electrical Engineering",
  "Executive Assistant",
  "Field Sales",
  "Financial Planning and Analysis",
  "Financial Reporting",
  "Founder",
  "Graphic Design",
  "Growth Marketing",
  "Hardware Engineering",
  "Healthcare Administration",
  "Help Desk",
  "HR Business Partner",
  "Industrial Design",
  "Inside Sales",
  "Intellectual Property",
  "Investment Banking",
  "IT Consulting",
  "IT Support",
  "Journalism",
  "Law Enforcement",
  "Learning and Development",
  "Leasing",
  "Logistics",
  "Management Consulting",
  "Manufacturing Operations",
  "Market Research",
  "Mechanical Engineering",
  "Medical Technician",
  "Military",
  "Network Administration",
  "Nursing",
  "Office Management",
  "Paralegal",
  "Partnerships",
  "Payroll",
  "Physician",
  "Procurement",
  "Product Design",
  "Product Management",
  "Product Marketing",
  "Product Operations",
  "Program Management",
  "Project Management",
  "Property Management",
  "Public Relations",
  "QA Engineering",
  "Quality Control",
  "Quality Engineering",
  "Real Estate Brokerage",
  "Reception",
  "Recruiting",
  "Research and Development",
  "Risk Management",
  "Sales Development",
  "Sales Engineering",
  "Sales Operations",
  "Scientific Research",
  "Scrum Master",
  "Security",
  "SEO/SEM",
  "Social Media",
  "Social Work",
  "Software Engineering",
  "Sourcing",
  "Strategic Alliances",
  "Strategy Consulting",
  "Supply Chain",
  "Systems Administration",
  "Talent Acquisition",
  "Tax",
  "Teaching",
  "Technical Product Management",
  "Technical Support",
  "Treasury",
  "UX/UI Design",
  "Vendor Management",
  "Volunteer Coordination",
]
