import { useState } from "react"
import {
  ArrowLeft,
  Calendar,
  Clock,
  CornerUpRight,
  Flag,
  Mail,
  Minus,
  Plus,
  type LucideIcon,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

// --- Ruleset constraints (v3.3) --------------------------------------------
const MIN_GAP = 1
const MAX_GAP = 45
const DEFAULT_TOUCHES = 3
const DEFAULT_GAPS: Gaps = { advancer: 6, closer: 17 }

interface Gaps {
  advancer: number
  closer: number
}

export interface SequenceConfig {
  touches: 2 | 3
  gaps: Gaps
  /** Closer style flips with shape: pure for 3-touch, soft for 2-touch. */
  closerStyle: "pure" | "soft"
}

interface StepMeta {
  icon: LucideIcon
  title: string
  subtitle: string
}

const OPENER: StepMeta = {
  icon: Mail,
  title: "The opener",
  subtitle: "Introduces you and why you are relevant.",
}
const ADVANCER: StepMeta = {
  icon: CornerUpRight,
  title: "The follow up",
  subtitle: "Returns with a fresh angle and a soft ask.",
}
const CLOSER: StepMeta = {
  icon: Flag,
  title: "The closer",
  subtitle: "Politely closes the loop and leaves the door open.",
}

interface SequenceBuilderProps {
  initialTouches?: 2 | 3
  initialGaps?: Gaps
  onPreview?: (config: SequenceConfig) => void
  /** Optional wizard "Back" affordance (kept left of the adjacent action pair). */
  onBack?: () => void
}

/**
 * Sequence Builder — defines a cold-outreach sequence's shape (2 or 3 touches)
 * and the delay between touches. Structure and cadence only; email content is
 * generated by the outreach engine elsewhere.
 */
export function SequenceBuilder({
  initialTouches = DEFAULT_TOUCHES,
  initialGaps = DEFAULT_GAPS,
  onPreview,
  onBack,
}: SequenceBuilderProps) {
  const [touches, setTouches] = useState<2 | 3>(initialTouches)
  // Both gaps are retained in state even in 2-touch mode so switching back to
  // 3-touch restores the previously entered advancer delay.
  const [gaps, setGaps] = useState<Gaps>(initialGaps)

  const closerStyle: SequenceConfig["closerStyle"] = touches === 3 ? "pure" : "soft"
  const activeGaps = touches === 3 ? [gaps.advancer, gaps.closer] : [gaps.closer]
  const span = activeGaps.reduce((a, b) => a + b, 0)
  const weeks = Math.round(span / 5)

  function setGap(key: keyof Gaps, value: number) {
    const clamped = Math.min(MAX_GAP, Math.max(MIN_GAP, value))
    setGaps((prev) => ({ ...prev, [key]: clamped }))
  }

  const config: SequenceConfig = { touches, gaps, closerStyle }

  return (
    <div className="space-y-6">
      <div className="space-y-6 lg:grid lg:grid-cols-[minmax(0,1fr)_320px] lg:gap-8 lg:space-y-0">
        <div className="space-y-6">
          {/* Shape toggle */}
          <div className="flex items-center justify-between gap-4">
            <span className="text-sm font-medium">How many emails?</span>
            <div className="inline-flex gap-1 rounded-lg bg-muted p-1">
              <ShapeSegment
                active={touches === 2}
                onClick={() => setTouches(2)}
                label="2 emails"
              />
              <ShapeSegment
                active={touches === 3}
                onClick={() => setTouches(3)}
                label="3 emails"
              />
            </div>
          </div>

          {/* Steps timeline */}
          <div>
            {touches === 3 ? (
              <>
                <StepNode n={1} meta={OPENER} />
                <DelayConnector
                  value={gaps.advancer}
                  onChange={(v) => setGap("advancer", v)}
                />
                <StepNode n={2} meta={ADVANCER} />
                <DelayConnector
                  value={gaps.closer}
                  onChange={(v) => setGap("closer", v)}
                />
                <StepNode n={3} meta={CLOSER} />
              </>
            ) : (
              <>
                <StepNode n={1} meta={OPENER} />
                <DelayConnector
                  value={gaps.closer}
                  onChange={(v) => setGap("closer", v)}
                />
                <StepNode n={2} meta={CLOSER} />
              </>
            )}
          </div>

          {/* Total summary */}
          <div className="flex items-center gap-2 rounded-lg border bg-muted/30 p-3 text-sm">
            <Calendar className="size-4 shrink-0 text-muted-foreground" />
            <span>
              {touches} emails over {span} working days, about{" "}
              {weeks === 1 ? "a week" : `${weeks} weeks`}
            </span>
          </div>
        </div>

        {/* What this means, in plain terms */}
        <aside className="h-fit rounded-lg border bg-muted/30 p-4">
          <p className="text-sm font-semibold">What this means</p>
          <div className="mt-2 space-y-2 text-sm leading-relaxed text-muted-foreground">
            <p>Email 1 goes out when the campaign starts.</p>
            {touches === 3 ? (
              <>
                <p>
                  Email 2 follows {gaps.advancer} working{" "}
                  {gaps.advancer === 1 ? "day" : "days"} later, trying a fresh
                  angle.
                </p>
                <p>
                  Email 3 politely closes the loop {gaps.closer} working{" "}
                  {gaps.closer === 1 ? "day" : "days"} after that.
                </p>
              </>
            ) : (
              <p>
                Email 2 politely closes the loop {gaps.closer} working{" "}
                {gaps.closer === 1 ? "day" : "days"} later.
              </p>
            )}
            <p>
              Waiting a few working days between emails is normal: it gives
              people room to reply without feeling chased.
            </p>
          </div>
          <p className="mt-3 border-t pt-3 text-xs text-muted-foreground">
            Next, ARIA drafts the wording and you choose your favourite for
            each email. Nothing sends by itself.
          </p>
        </aside>
      </div>

      {/* Actions */}
      <div
        className={cn(
          "flex items-center gap-2",
          onBack ? "justify-between" : "justify-end",
        )}
      >
        {onBack && (
          <Button type="button" variant="ghost" onClick={onBack}>
            <ArrowLeft className="size-4" />
            Back
          </Button>
        )}
        <Button type="button" onClick={() => onPreview?.(config)}>
          Preview the emails
        </Button>
      </div>
    </div>
  )
}

function ShapeSegment({
  active,
  onClick,
  label,
}: {
  active: boolean
  onClick: () => void
  label: string
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={cn(
        "rounded-md px-3 py-1.5 text-sm transition-colors",
        active
          ? "bg-background font-medium text-foreground shadow-sm"
          : "text-muted-foreground hover:text-foreground",
      )}
    >
      {label}
    </button>
  )
}

function StepNode({ n, meta }: { n: number; meta: StepMeta }) {
  const Icon = meta.icon
  return (
    <div className="flex items-center gap-4">
      <div className="flex w-10 shrink-0 justify-center">
        <span className="flex size-10 items-center justify-center rounded-full border bg-background">
          <Icon className="size-5 text-muted-foreground" />
        </span>
      </div>
      <div className="min-w-0">
        <p className="font-medium">
          {n}. {meta.title}
        </p>
        <p className="text-sm text-muted-foreground">{meta.subtitle}</p>
      </div>
    </div>
  )
}

function DelayConnector({
  value,
  onChange,
}: {
  value: number
  onChange: (value: number) => void
}) {
  return (
    <div className="flex items-stretch gap-4">
      {/* Dashed rule aligned under the circular markers above and below. */}
      <div className="flex w-10 shrink-0 justify-center">
        <div className="border-l border-dashed border-border" />
      </div>
      <div className="flex items-center gap-2 py-3 text-sm">
        <Clock className="size-4 text-muted-foreground" />
        <span>wait</span>
        <Button
          type="button"
          variant="outline"
          size="icon-xs"
          onClick={() => onChange(value - 1)}
          disabled={value <= MIN_GAP}
          aria-label="Decrease delay"
        >
          <Minus className="size-3" />
        </Button>
        <span className="w-6 text-center tabular-nums font-medium">{value}</span>
        <Button
          type="button"
          variant="outline"
          size="icon-xs"
          onClick={() => onChange(value + 1)}
          disabled={value >= MAX_GAP}
          aria-label="Increase delay"
        >
          <Plus className="size-3" />
        </Button>
        <span className="text-muted-foreground">working days</span>
      </div>
    </div>
  )
}
